Update README.md
maulana1k/dreamwalking pull request #1
Opened 2023-05-18 05:37 UTC by Rollerturtle

adding desc to the project

2023-05-18 15:59 UTC, maulana1k requested changes
tambahin tian

2023-05-19 03:04 UTC, maulana1k requested changes

2023-05-19 03:04 UTC, maulana1k commented on README.md
> +
nim tian

2023-05-19 04:38 UTC, Tiannns commented on README.md
> +
**Septian Aldi Zakaria** - *H1D021032* - [Tiannns](https://github.com/Tiannns)

2023-05-19 07:17 UTC, closed without merging